name: Token
author: $author
version: $version
api-version: 1.16
main: $main

commands:
  token:
    description: You can get some tokens.
    usage: /token <options> <type> <amount>

permissions:
  token.op:
    description: Op's Command
    default: op